name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Build Docker image
      run: docker build -t kaur_manveer_coding_assignment14 .

    - name: Push Docker image to Docker Hub
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push kaur_manveer_coding_assignment14

    # Add a step to build Storybook
    - name: Build Storybook
      run: npm run storybook:build
      
